### ISSUE TITLE
ridicolous amounts of time to convert to 60fps

### ISSUE THREAD

**Issue by programreviewer345** [mysteryx93/NaturalGroundingPlayer#1]
It's atrocious

**Comment by mysteryx93** [comment]
Converting videos can be time-consuming, depending on your system and settings. On my Quad-core i7 with Radeon HD 7670M, it takes almost an hour per video of 4 minutes. Note that neither the CPU nor the GPU is fully used, as the bottleneck seems to be on data transfers. When using Intel HD 4000 GPU instead of Radeon, performance difference is minimal.

**Comment by mysteryx93** [comment]
Oh, there is one thing that makes a difference specifically for 60fps conversion. It is done by Interframe command. By default, I enable GPU-acceleration only if you activated madVR under settings. Enable it either by enabling madVR, or add "GPU=true" to the Interframe command in the AviSynth Script tab.

I'll change it to be always true, as other filters now require GPU acceleration anyway.

Then if it's too slow for you because of the other processing, don't upscale the image, or disable SuperRes. The more processing you do, the longer it takes.

**Comment by programreviewer345** [comment]
I want to convert my movies to 60fps since SVP hasn't been working for me anymore, so you're saying it will take...many days to convert a movie? I did successfully convert one but then it was in fast motion(like 60fps AND at 4.0x speed), is that because it was originally 24fps? and sorry my original post was rude it's just frustrating to me, I don't want denoise and super res and crop and all that stuff, I Just want my original video converted to 60fps(deinterlacing is ok though), and I want it to not take alot of time since when my computer is encoding the videos with your program it slows down all my other processes(since I increase priority to Normal?). Also there's another problem sometimes when I encode it says an exe has stopped working(avs2 i think) and the only way to stop it is to uninstall/reinstall your program. Any idea why?

**Comment by programreviewer345** [comment]
Also, why can't I save script settings? When I go to change script i can't save, it just lets me encode the video and i can't save the script for next time

**Comment by mysteryx93** [comment]
If you only want to convert to 60fps, make sure all other options are disabled and that you're not upscaling the resolution of the video. SVP itself shouldn't be much slower than when playing it live, except that its settings will be higher. "Smooth" settings are a bit heavier. Then what settings are you using for encoding? x265-Medium is working well for me. You can put it to Faster.
As for avs2yuv crashing, it's stable on my computer so I don't know. Generally, if a process doesn't close properly, you can find it in Task Manager and end the task manually. If not, rebooting works for sure.

**Comment by programreviewer345** [comment]
SVP has been skipping and lagging and screen tearing I have no idea why since it was working perfectly just a few days ago. Videos converted to 60fps with your program work fine. And don't i need denoise and deinterlace or else the video looks crappy? Or is that only if the original video had noise and interlace problems. Thanks for your help

**Comment by programreviewer345** [comment]
Now it's doing 0.20 seconds per second instead of 0.4, small improvement but still appreciated

**Comment by programreviewer345** [comment]
Now with no settings set and faster setting the video looks like 240p....

**Comment by mysteryx93** [comment]
It will only look like 240p if you set the output height to 240...

If SVP is lagging on your computer, perhaps GPU-acceleration got deactivated for some reason? This problem would be for the SVP forum. http://www.svp-team.com/forum/

**Comment by programreviewer345** [comment]
I didn't set the height to anything, I let it at default. It just really made the video look like crap after conversion.

**Comment by mysteryx93** [comment]
Then that's why. You're probably downscaling a 1080p video to 768p then. In computer terms, that's a "code 18" error; meaning the error is 18 inches away from the screen :P

**Comment by mysteryx93** [comment]
If you're not having any luck with the automated process, you can do it manually by following this guide, which would help you understand how it works.
http://www.spirton.com/convert-videos-to-60fps/

**Comment by programreviewer345** [comment]
Do I need denoise, deinterlace? Or are they just optional, and what about super res, what are the benefits of super res

**Comment by programreviewer345** [comment]
And I started out with that guy's guide but MEGUI didn't work for me always giving errors when video conversion reached 99%, but yours usually works except for the speed....

**Comment by mysteryx93** [comment]
Only denoise if there is noise and see what settings look best. That's what preview is for. Also, removing noise makes encoding more efficient as it encodes more of the "real data" instead of encoding the noise. I haven't added any deinterlacing, so it might not work well with interlaced content. SuperRes is only when upscaling (such as 288p to 720p), it makes the result much better. Also, in Task Manager, you can see what is taking most of the encoding time. "avs2yuv" is running the AviSynth script while "ffmpeg" is running the encoding process. If encoding takes too long, you can lower the settings to make that part faster.

**Comment by programreviewer345** [comment]
thanks

**Comment by programreviewer345** [comment]
One more question, if I compress a video first before converting to 60fps, will it reduce conversion time?

**Comment by mysteryx93** [comment]
Compression first? You'd just throw away quality because it needs to be encoded twice, and it needs to be decoded before processing. Look at the raw script to see if there are parts of it that are unnecessary.

**Comment by programreviewer345** [comment]
Ok I am compresing a 2 hour 30 minute movie right now I started last night and it is only done 40 mins of the movie so far at 1pm, but I guess I can wait as the encoding only takes a small bit of performance.

**Comment by programreviewer345** [comment]
but it's gonna piss me off if it doesnt do it right with this long of a wait

**Comment by programreviewer345** [comment]
increasing priority of ffmpeg and avs2yuv makes it slightly faster

**Comment by mysteryx93** [comment]
You can also first Trim the video to encode only 10 seconds to test before doing the whole thing.

Also, removing "Smooth" from Increase Frame Rate makes it faster.

InterFrame has other settings allowing to run it faster.
http://www.spirton.com/uploads/InterFrame/InterFrame2.html

**Comment by programreviewer345** [comment]
I like smooth though, I think its worth it to leave smooth on

**Comment by programreviewer345** [comment]
you should allow saving avisynth script changes and then going back to edit other settings. when i change settings in script all I can do is encode and I lose those settings next time. Of course, allow a revert to default if you screw up the script

**Comment by programreviewer345** [comment]
also can you make it so I can change to exact FPS i want, 48 for example, or is that already a feature I just haven't figured it out? I can do it for 24fps videos by selecting "Double" framerate, but what about 30fps vids?

**Comment by mysteryx93** [comment]
I cannot preserve the script when editing settings because the script must be regenerated.

To set a custom frame rate, you can alter InterFrame command in the script. Replace '60' with '48'.

**Comment by programreviewer345** [comment]
when I choose very fast in settings it does it quickly but i get no video just audio

**Comment by programreviewer345** [comment]
Ok I chose x264 instead of 5 and it works but for some reason framerate fluctuates(seeing with MPC statistics view) it goes from 40 to 44 and then to 48, why not consistent 48?

**Comment by programreviewer345** [comment]
Nevermind, was probably inaccurate calculation because when I set video to replay after finish it is either 47 to 48(normal with videos to do that though)

**Comment by programreviewer345** [comment]
Converting to 48fps is alot faster than converting to 60 and i still retain acceptable quality

**Comment by programreviewer345** [comment]
why is trim section greyed out?

**Comment by programreviewer345** [comment]
converted videos actually have very little to no quality loss, I was just using problematic video players like media player classic and potplayer that severely artifact videos, it's great now with splash player
