### ISSUE TITLE
Problems with statrtup

### ISSUE THREAD

**Issue by guydht** [mysteryx93/NaturalGroundingPlayer#2]
Every time I start the application it writes me the same error message: Unhandled exception........ The invocation of the constructor on type 'MediaPlayer.WindowsMediaPlayer'

I tried re-installing the program a number of times but it didn't fix anything....... It worked fine up until now but suddenly it kept showing this error message, that even re-installing doesn't solve...... It has nothing to do with Windows Media Player, because I never had it installed on my computer in the first place, and it did work for a while...... So I have no idea what's up with it. Here's the log file it keeps showing me:
[Log.txt](https://github.com/mysteryx93/NaturalGroundingPlayer/files/276071/Log.txt)

**Comment by mysteryx93** [comment]
The fact that you never had it installed is why it is complaining about it. Perhaps you accidentally changed the player from MPC-HC to Internal under settings? Internal player uses Windows Media Player.

**Comment by guydht** [comment]
Okay..... So how can I fix it? I mean, I can't launch the application because of the error, so I can't change the internal player option........ I rather not install windows media player just for changing this option...... Because I'm not going to use it.......

**Comment by mysteryx93** [comment]
The application doesn't start "at all" ? Generally when it crashes, it just displays the message and let you continue.

Either way, here's another way to change it.
Open this file in Notepad
My Documents\Natural Grounding Player\Settings.xml

Change this value to Mpc
<MediaPlayerApp>Mpc</MediaPlayerApp>

Save & close.

**Comment by guydht** [comment]
Never mind, I fixed it. I just changed the "MediaPlayerApp" element in the xml "setting.xml" file to "MPC" and it worked. Thanks for the feedback!

**Comment by guydht** [comment]
Okay, so now the app launches but when I try to use the media encoder, it still shows me the exact same error and doesn't launch the "media encoder" window...... Here's the log, again:
[Log.txt](https://github.com/mysteryx93/NaturalGroundingPlayer/files/276260/Log.txt)
And here's my setting XML file: (I changed it to a .txt file because I can't send xml files through this site)
[Settings.txt](https://github.com/mysteryx93/NaturalGroundingPlayer/files/276261/Settings.txt)

**Comment by mysteryx93** [comment]
The Preview buttons won't work because it opens it in Windows Media Player. Use "Preview in MPC-HC" instead.

**Comment by guydht** [comment]
It's not the preview buttons that don't work, when I press the "Tools" tab and then press the "Media Encoder....." option, it displays that error and does nothing.

**Comment by mysteryx93** [comment]
Oh. I see. In that case, either you install Windows Media Player, or you'll have to wait until I release an updated version that fixes that.

**Comment by guydht** [comment]
But before this whole issue started I was able to enter that "Media Encoder" page...... Maybe it has something to do with some settings again?

**Comment by mysteryx93** [comment]
Perhaps it worked in a previous version, but this version won't load if WMP isn't installed. I could give you a beta of the next version when it's ready to test whether it works fine on a non-WMP machine as I cannot test it on my machine.

**Comment by vixing** [comment]
Can you give us this beta? I can't install WMP on my machine, so I keep getting that error.

**Comment by mysteryx93** [comment]
Does v1.4 still have this issue?
https://github.com/mysteryx93/NaturalGroundingPlayer/releases/tag/v1.4
