### ISSUE TITLE
Support for HEVC / x265 source files

### ISSUE THREAD

**Issue by dejavecue** [mysteryx93/NaturalGroundingPlayer#3]
The YinMediaEncoder works as intended for any file that is not encoded with x265. Those files simply produce a green output file - no picture (sound gets passed through).

Could support for hevc files be added so we can frame interpolate them as well?

**Comment by mysteryx93** [comment]
Occasionally there can be video files that won't open properly using the default method. In such cases, check "Convert to AVI" and in most cases it will work just fine. Let me know if that doesn't resolve your issue.

**Comment by dejavecue** [comment]
This works, thank you. It was not obvious to me, so maybe it should be added to the readme.

Thank you for your quick help.
