### ISSUE TITLE
Yin Media Encoder: Cannot convert 2160p video?

### ISSUE THREAD

**Issue by an0ndev** [mysteryx93/NaturalGroundingPlayer#4]
Hi,

I've really appreciated your converter over the past few months, but yesterday, I had some unknown problem.  As soon as FFMPEG launches, it gets this far before hanging there.  I left it on overnight (~12 hours) with no result.

Here's the output: 
[ffmpeg-output.txt](https://github.com/mysteryx93/NaturalGroundingPlayer/files/1272990/ffmpeg-output.txt) (I had to upload it in a text file as Markdown seems to break line breaks in code.)

And that's it.  I do have a process called "avs2yuv.exe" running in the background, but it stays locked at 1.6 MB memory usage, 0% CPU and 0 MB/s disk usage.

The output file in C:\Natural Grounding\Temp stays locked at 0 bytes the entire time.  I have attached the script and settings from that folder here: [Job11.zip](https://github.com/mysteryx93/NaturalGroundingPlayer/files/1272984/Job11.zip)

I have also attached a MediaInfo output of the original file here: 
[MediaInfo.txt](https://github.com/mysteryx93/NaturalGroundingPlayer/files/1272985/MediaInfo.txt)

Thanks in advance,

HewwoCraziness

**Comment by mysteryx93** [comment]
Did you try "Convert to AVI"?

**Comment by HewwoCraziness** [comment]
Just did.  Same issue except that avs2yuv.exe now is locked at 1,364.7 MB memory usage.
