### ISSUE TITLE
How to use this repo to download live stream m3u8 URL and save to local hard drive?

### ISSUE THREAD

**Issue by zydjohnHotmail** [mysteryx93/NaturalGroundingPlayer#9]
Hello:
I happen to find your repo, and it seems to be interesting. However, as it is rather complicated, 
I can’t figure out yet how to download multiple M3U8 videos and save to local hard drive.
For example, I have the following 2 M3U8 videos in the URL:
http://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel.ism/.m3u8
http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
I want to launch 2 clients to download them at the same time, when finished, I want to save the files as local files: C:\1.mp4 and C:\2.mp4 and stop or dispose the client.
Please show me how I can do this with C#.
By the way, I am using Windows 10 Version 21H1, and Visual Studio 2019 Version 16.10.4.
Thanks,

**Comment by mysteryx93** [comment]
Better look into a library like this for example of how to download files or streams
https://github.com/Tyrrrz/YoutubeExplode
